# docker-compose.yml
version: "2"
services:
  csua-backend:
    build: .
    environment:
      - DJANGO_SECRET_KEY=poop
      - DJANGO_DEBUG=True
      - MYSQL_USER=pnunez
      - MYSQL_PASSWORD=forwardA1r2t3hBL4STz0ne!
      - MYSQL_DATABASE=csua_backend
    networks:
      - main
    depends_on:
      - db
    volumes:
      - ./apps:/app/apps
      - ./templates:/app/templates
      - ./static:/app/static_root
      - ./Pipfile:/app/Pipfile
      - ./Pipfile.lock:/app/Pipfile.lock
        #command: gunicorn --bind 0.0.0.0:8001 apps.csua_backend.wsgi
    command: gunicorn --bind 0.0.0.0:8001 --reload apps.csua_backend.wsgi
  csua-backend-test:
    build: .
    environment:
      - DJANGO_SECRET_KEY=poop
      - DJANGO_DEBUG=True
      - MYSQL_USER=pnunez
      - MYSQL_PASSWORD=forwardA1r2t3hBL4STz0ne!
      - MYSQL_DATABASE=csua_backend
    networks:
      - main
    depends_on:
      - db
    volumes:
      - ./apps:/app/apps
      - ./templates:/app/templates
      - ./static:/app/static_root
    command: watchmedo auto-restart --recursive --debug-force-polling --pattern="*.py" --directory="." -- python manage.py test

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=csua_backend
      - MYSQL_USER=pnunez
      - MYSQL_PASSWORD=forwardA1r2t3hBL4STz0ne!
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - main
    volumes:
      - ./mysql_data/:/var/lib/mysql

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/csua_backend/static
    ports:
      - "8080:80"
    depends_on:
      - csua-backend
    networks:
      - main

networks:
  main:

# vim: et:sw=2:ts=2:sts=2
