[project]
name = "csua-backend"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "django (>=2.2,<3.0)",
    "django-markdown-deux (>=1.0.6,<2.0.0)",
    "pillow (>=11.2.1,<12.0.0)",
    "sorl-thumbnail (==12.10.0)",
    "python-decouple (>=3.8,<4.0)",
    "django-python3-ldap (>=0.15.8,<0.16.0)",
    "ldap3 (==2.8)",
    "requests (>=2.32.3,<3.0.0)",
    "djangorestframework (>=3.13.1,<4.0.0)",
    "slack-bolt (>=1.23.0,<2.0.0)",
    "discord-py (>=2.5.2,<3.0.0)",
    "schedule (>=1.2.2,<2.0.0)",
    "pyfiglet (>=1.0.2,<2.0.0)",
    "cowpy (>=1.1.5,<2.0.0)",
    "google-api-python-client (>=2.0.0)",
    "setuptools (>=79.0.0,<80.0.0)",
    "mysqlclient (>=2.2.7,<3.0.0)",
    "django-widget-tweaks (>=1.5.0,<2.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)"
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
black = "^25.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
