# Generated by Django 2.0.6 on 2018-08-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tracker", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tracker.User",
            ),
        )
    ]
