# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db_data", "0006_officer_root_staff")]

    operations = [
        migrations.AddField(
            model_name="officer",
            name="tutor_subjects",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        )
    ]
