# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-27 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_data", "0008_event")]

    operations = [
        migrations.AlterField(
            model_name="officer",
            name="tutor_subjects",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
