# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db_data", "0008_event")]

    operations = [
        migrations.AlterField(model_name="sponsor", name="url", field=models.URLField())
    ]
