# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-01 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_data", "0009_auto_20171101_0119"),
        ("db_data", "0009_auto_20171026_2330"),
    ]

    operations = []
