# Generated by Django 2.0.6 on 2018-06-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("db_data", "0010_merge")]

    operations = [
        migrations.AddField(
            model_name="officer",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="politburo",
            name="officer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="db_data.Officer"
            ),
        ),
    ]
