# Generated by Django 2.0.6 on 2019-06-23 07:50

import apps.db_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("db_data", "0013_officer_officer_since")]

    operations = [
        migrations.CreateModel(
            name="Officership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blurb", models.CharField(max_length=255)),
                ("office_hours", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "user",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "photo1",
                    models.ImageField(
                        default="images/officers/cardigan.jpg",
                        max_length=255,
                        upload_to=apps.db_data.models.person_photo_path,
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        upload_to=apps.db_data.models.person_photo_path_alt,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolitburoMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="db_data.Person"
                    ),
                ),
                (
                    "politburo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db_data.Politburo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("current", models.BooleanField()),
                ("name", models.CharField(max_length=16)),
                ("events", models.ManyToManyField(to="db_data.Event")),
            ],
        ),
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db_data.Semester",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UcbClass",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                )
            ],
        ),
        migrations.RemoveField(model_name="officer", name="blurb"),
        migrations.RemoveField(model_name="officer", name="first_name"),
        migrations.RemoveField(model_name="officer", name="id"),
        migrations.RemoveField(model_name="officer", name="last_name"),
        migrations.RemoveField(model_name="officer", name="office_hours"),
        migrations.RemoveField(model_name="officer", name="photo1"),
        migrations.RemoveField(model_name="officer", name="photo2"),
        migrations.RemoveField(model_name="officer", name="tutor_subjects"),
        migrations.RemoveField(model_name="sponsor", name="current"),
        migrations.RemoveField(model_name="sponsor", name="description"),
        migrations.AddField(
            model_name="sponsorship",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db_data.Sponsor"
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="officers",
            field=models.ManyToManyField(
                through="db_data.Officership", to="db_data.Officer"
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="politburo",
            field=models.ManyToManyField(
                through="db_data.PolitburoMembership", to="db_data.Politburo"
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="sponsors",
            field=models.ManyToManyField(
                through="db_data.Sponsorship", to="db_data.Sponsor"
            ),
        ),
        migrations.AddField(
            model_name="politburomembership",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db_data.Semester"
            ),
        ),
        migrations.AddField(
            model_name="officership",
            name="officer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db_data.Officer"
            ),
        ),
        migrations.AddField(
            model_name="officership",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db_data.Semester"
            ),
        ),
        migrations.AddField(
            model_name="officership",
            name="tutor_subjects",
            field=models.ManyToManyField(to="db_data.UcbClass"),
        ),
        migrations.AddField(
            model_name="officer",
            name="person",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                serialize=False,
                to="db_data.Person",
            ),
            preserve_default=False,
        ),
    ]
