# Generated by Django 2.0.6 on 2019-06-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_data", "0015_auto_20190623_0102")]

    operations = [
        migrations.RemoveField(model_name="person", name="first_name"),
        migrations.RemoveField(model_name="person", name="last_name"),
    ]
