# Generated by Django 2.2.9 on 2020-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_data", "0015_auto_20191017_1438")]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="id",
            field=models.CharField(
                help_text="Used for URLs, should match /(fa|sp)[0-9]{2}/",
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        )
    ]
