# Generated by Django 2.0.6 on 2019-06-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("db_data", "0017_remove_officer_enabled")]

    operations = [
        migrations.AddField(
            model_name="officer",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="officer",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="db_data.Person"
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="officers",
            field=models.ManyToManyField(
                blank=True, through="db_data.Officership", to="db_data.Officer"
            ),
        ),
    ]
