# Generated by Django 2.2.12 on 2020-07-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_data", "0018_auto_20200723_2120")]

    operations = [
        migrations.AlterField(
            model_name="officer",
            name="officer_since",
            field=models.DateField(null=True),
        )
    ]
