# Generated by Django 2.0.6 on 2019-06-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("db_data", "0019_person_video2")]

    operations = [
        migrations.RemoveField(model_name="politburo", name="officer"),
        migrations.AlterField(
            model_name="politburomembership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="db_data.Person"
            ),
        ),
    ]
