# Generated by Django 2.0.6 on 2019-06-24 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("db_data", "0020_auto_20190623_1836")]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(model_name="event", name="enabled"),
        migrations.AlterField(
            model_name="event", name="link", field=models.URLField(blank=True)
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="db_data.EventCategory",
            ),
        ),
    ]
