# Generated by Django 2.2.28 on 2025-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_data", "0021_auto_20210515_1807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officership",
            name="blurb",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
