# Generated by Django 2.2.19 on 2021-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_data", "0021_auto_20210515_1807")]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="date_time", new_name="start_time"
        ),
        migrations.AddField(
            model_name="event", name="end_time", field=models.DateTimeField(null=True)
        ),
    ]
