# Generated by Django 2.2.28 on 2025-04-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_data", "0022_auto_20250128_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorship",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
