---
# This ansible playbook deploys this application to the site
# It currently only refreshes the deploy on the production server
# It doesn't set up the site on a clean machine (yet)

# NOTE: The pip modules (e.g. Django) installed in www-data's user directory
# (/var/www/.local/lib/python3.5/site-packages) will supercede the modules
# installed in the system's global installation directory
# (/usr/local/lib/python3.5/dist-packages)

# RUN USING:
# ansible-playbook deploy.yml -i hosts -K

- hosts: tap
  become: www-data
  tasks:
  - name: checkout master
    git:
        repo: 'git@github.com:CSUA/CSUA-backend'
        dest: /webserver/CSUA-backend/
        version: master
  - name: install python requirements
    pip:
        requirements: /webserver/CSUA-backend/requirements.txt
        executable: pip3
  - name: ensure mod_wsgi is enabled
    # only root has access to the certificate files, won't run as www-data
    become_user: root
    become: true
    apache2_module: name=wsgi state=present
    # need to restart apache2 to reload wsgi
  - name: restart apache2
    become_user: root
    become: true
    service: name=apache2 state=restarted
