- hosts: tap
  become: www-data
  tasks:
  - name: checkout master
    become: true
    become_user: www-data
    git:
        repo: 'git@github.com:CSUA/CSUA-backend'
        dest: /webserver/CSUA-backend-dev/
        version: dev
  - name: install python requirements
    pip:
        requirements: /webserver/CSUA-backend-dev/requirements.txt
        executable: pip3
  - name: ensure mod_wsgi is enabled
    # only root has access to the certificate files, won't run as www-data
    become_user: root
    become: true
    apache2_module: name=wsgi state=present
    # need to restart apache2 to reload wsgi
  - name: restart apache2
    become_user: root
    become: true
    service: name=apache2 state=restarted
# vim: et ts=2 sw=2 sts=2
