# Generated by Django 2.2.19 on 2021-03-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("discordbot", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ConnectFourGame",
            fields=[
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("player1", models.IntegerField()),
                ("player2", models.IntegerField()),
                ("is_player1_turn", models.BooleanField(default=True)),
                ("winner", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(max_length=255)),
            ],
        )
    ]
