# Generated by Django 2.2.19 on 2021-03-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("discordbot", "0002_connectfourgame")]

    operations = [
        migrations.AlterField(
            model_name="connectfourgame", name="state", field=models.TextField()
        )
    ]
