# Generated by Django 2.2.19 on 2021-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("discordbot", "0004_auto_20210321_0152")]

    operations = [
        migrations.AlterField(
            model_name="connectfourgame",
            name="player1",
            field=models.BigIntegerField(help_text="Discord User ID of player 1"),
        ),
        migrations.AlterField(
            model_name="connectfourgame",
            name="player2",
            field=models.BigIntegerField(help_text="Discord User ID of player 2"),
        ),
        migrations.AlterField(
            model_name="connectfourgame",
            name="winner",
            field=models.IntegerField(
                blank=True,
                help_text="Null if no winner, 1 or 2 if winner exists",
                null=True,
            ),
        ),
    ]
