# Generated by Django 3.2 on 2025-04-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discordbot", "0007_anishufflegame_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordregistereduser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
