#!/bin/bash
#!/bin/rbash
#arguments: config_newuser username email uid enroll_jobs
if [ $# -ne 4 ]; then echo "usage: $0 username email uid enroll_jobs"; exit 1; fi
mkdir -m 700 /nfs/homes/$1
echo $2 > /nfs/homes/$1/.forward
chown -R $3:1000 /nfs/homes/$1
# TODO: add back mailman enrollment
#echo $2 | add_members -r - Csua-newmembers
#if ($4); then echo $2 | add_members -r - Jobs; fi

# Enroll user in csua-members google group (temp solution until mailman)
/root/root-work/auto-list-update/addMember.py $2

#this is for creating the public_html folder and link
mkdir -m 755 /nfs/public_html/$1
chown -R $3:1000 /nfs/public_html/$1
ln -s /csua/public_html/$1 /nfs/homes/$1/public_html
