# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 18:00


import db_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_data', '0004_auto_20161105_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=70)),
                ('photo', models.ImageField(default='images/officers/cardigan.jpg', max_length=255, upload_to=db_data.models.sponsor_photo_path)),
                ('description', models.CharField(max_length=255)),
                ('current', models.BooleanField(default=True)),
            ],
        ),
    ]
