name: Django CI

on: [push, pull_request]

env:
  DJANGO_SECRET_KEY: pnunez1
  NEWUSER_PW: pnunez2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Read deploy script contents
        uses: andstor/file-reader-action@v1.0.0
        id: deploy_script
        with:
          path: scripts/deploy.sh
      - name: Run deployment script if master branch updated
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          proxy_host: ${{ secrets.DEPLOY_PROXY_HOST }}
          proxy_username: ${{ secrets.DEPLOY_PROXY_USERNAME }}
          proxy_key: ${{ secrets.DEPLOY_PROXY_KEY }}
          proxy_port: ${{ secrets.DEPLOY_PROXY_PORT }}
          script: ${{ steps.deploy_script.outputs.contents }}

